71 user roles
fidel-bello/epic-poggers-ecomstore pull request #82
Opened 2022-05-14 02:41 UTC by fidel-bello

# Pull request

## Description

[//]: # (Summary of changes. List any dependency changes required for this change)
![image](https://user-images.githubusercontent.com/73322116/168407858-6a0e25ea-68cb-422c-a371-c13a1d0eb706.png)
if a user role tries to access admin, it will cause a fail or error

## Type of Change

- [ ] Refactor (non-breaking change which improves code performance or readability)
- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change that adds functionality)
- [ ] Documentation (changes to docs and not code)
- [ ] Breaking Change (Fix or change that would cause existing functionality to not work as expected)
- [ ] Test

## How it was tested

Enter description of testing

- [ ] Unit Test
- [x] Manual / Postman(if backend)
- [ ] Integration

## Affirmations

- [x] I follow coding guidelines (TBD)
- [x] I have self-reviewed my code
- [ ] I have run eslint and fixes issues (Mostly works but needs more rules and a fix)
- [ ] I have commented code when necessary or difficult
- [ ] I have made changes to docs where required
- [x] My changes generate no new warnings
- [x] I have added tests
- [x] New and existing tests pass

2022-05-14 02:47 UTC, ivan-ngchakming commented on Backend/src/app/models/user.ts
> +        default: Date.now()
Are you sure? In my experience, its usually the function that gets passed as default.

2022-05-14 02:51 UTC, fidel-bello reviewed
yes.. according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now that is the correct syntax. but it works either way. im just going based off the docs.

2022-05-14 03:00 UTC, nmp14 commented on Backend/src/app/models/user.ts
> +        default: Date.now()
Date.now will save a function that returns the time on a user creation.
Date.now() will return the time of schema creation as it gets called immediately. Probably not ideal.

2022-05-14 03:03 UTC, fidel-bello commented on Backend/src/app/models/user.ts
> +        default: Date.now()
oh I see now, thanks for the explanation will change now.

2022-05-14 03:05 UTC, ivan-ngchakming commented on Backend/src/app/models/user.ts
> +        default: Date.now()
> yes.. according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now that is the correct syntax. but it works either way. im just going based off the docs.

@fidel-bello It doesn't work, note the creation timestamps of each user

![image](https://user-images.githubusercontent.com/97230812/168408425-a99507bf-3271-46b9-a8e4-1229649a46c4.png)

2022-05-14 03:09 UTC, ivan-ngchakming commented on Backend/src/app/controllers/authControllers.ts
> +import process from "process";
Why is this import required?

2022-05-14 03:14 UTC, ivan-ngchakming requested changes
Looks good in general, just a minor typing issue

2022-05-14 03:14 UTC, ivan-ngchakming commented on Backend/src/app/controllers/authControllers.ts
> +import process from "process";
Why is this import required?

2022-05-14 03:14 UTC, ivan-ngchakming commented on Backend/src/app/controllers/authControllers.ts
> +    public authorizeRoles = (...roles: any[]) =>  {
I don't think it is a good practice to use any, weird eslint/ts didnt catch this.

```suggestion
    public authorizeRoles = (...roles: Role[]) =>  {
```

And create a Role enum:
```js
    enum Role {
        Admin = 'admin',
        ...
    }
```

2022-05-14 03:14 UTC, ivan-ngchakming commented on Backend/src/app/models/user.ts
> +        default: 'user'  //defaults to normal user
Use the Role enum mentioned above

2022-05-14 03:14 UTC, ivan-ngchakming commented on Backend/src/app/routes/productRoutes.ts
> +router.route('/admin/products/new').post(User.isAuthenticated, User.authorizeRoles('admin'), Product.createProducts);
Use the Role enum mentioned above

2022-05-14 03:17 UTC, fidel-bello commented on Backend/src/app/controllers/authControllers.ts
> +import process from "process";
its not.. i was trying to do something with process.env and it automatically imported.. sorry didnt mean to

2022-05-14 03:32 UTC, ivan-ngchakming commented on Backend/src/app/controllers/authControllers.ts
> +import process from "process";
hey don't be sorry, gosh knows how many time I've committed mistakes like this to a PR. vscode should be the one who's sorry for not being smart enough

2022-05-17 06:58 UTC, ivan-ngchakming submitted a review, later dismissed
Looks good, just a few final suggestions

2022-05-17 06:58 UTC, ivan-ngchakming commented on Backend/src/app/controllers/authControllers.ts
> +               return next(new Error_Handler(`Role: "${UserRole.admin}" is not allowed to access this route`, 403));
```suggestion
            if(!roles.includes(req.user.role))
               return next(new Error_Handler(`Role: "${req.user.role}" is not allowed to access this route`, 403));
```

2022-05-17 06:58 UTC, ivan-ngchakming commented on Backend/src/app/controllers/authControllers.ts
> +    admin = 'admin'
Missed the default user role?

```suggestion
    Admin = 'admin',
    User = 'user',
```

2022-05-17 07:16 UTC, ivan-ngchakming commented on Backend/src/app/models/user.ts
> +        default: 'user'  //defaults to normal user
My bad, missed one comment from last review

```suggestion
        default: UserRole.User  //defaults to normal user
```

2022-05-20 15:49 UTC, merged